### ISSUE TITLE
Wonky interface of detach and run_in_main

### ISSUE THREAD

**Issue by aantron** [hcarty/mwt#1]
I was just looking at this in Lwt. Why is `detach : ('a -> 'b) -> 'a -> 'b Lwt.t`, but `run_in_main : (unit -> 'a Lwt.t) -> 'a`? Can't we make both function arguments take unit, or some non-trivial argument? These will then be visual duals of each other.

I haven't thought about this very deeply, but I'm wondering about your opinion, since you've been giving this module attention.

Something like this seems much nicer:

```ocaml
detach      : ('a -> 'b) -> ('a -> 'b Lwt.t)
run_in_main : ('a -> 'b Lwt.t) -> ('a -> 'b)
```

or simply

```ocaml
detach      : (unit -> 'a) -> 'a Lwt.t
run_in_main : (unit -> 'a Lwt.t) -> 'a
```

**Comment by hcarty** [comment]
Good question.  I haven't really messed with `run_in_main` at all but this seems like a very reasonable API change.  I'll take a look.

**Comment by hcarty** [comment]
The change would be simple in either case.  The `unit` case seems a little cleaner, particularly if the called function has multiple arguments so I'll push that here into `Mwt` to see how it looks.

**Comment by hcarty** [comment]
See 538319ce1930c1633e749d45e9bb30503c1a8563

**Comment by aantron** [comment]
Looks good. I agree that `unit` is the cleaner choice. Haven't looked in the history, so speculating, but perhaps the ability to pass an argument to `detach` was just carried over from `Thread.create`.
